### ISSUE TITLE
Save to mongo with radio button

### ISSUE THREAD

**Issue by Zaidwerd** [Zaidwerd/stay-at-home#1]
@rapala61

Hey Rafa,

This could be an easy fix but I am having trouble with my form in generator.ejs. Since I am grabbing from two API's I am using a radio button to select one of the three movies and one of the three recipes. the issue is that the submit button will save all the options. 
- I tried moving the submit button inside the for loop but it would only save one movie and skip the recipe, or vice versa. 
- I also thought of breaking up the page into separate search result pages but I rather have it done this way. 
- Lastly I was thinking of making another js file that would run a function that loops through the radio buttons and grabs the data but I am not sure how to link everything together. 

Could you point me in the right direction.

Thanks,
Andrew

<img width="705" alt="screen shot 2016-10-27 at 3 24 50 pm" src="https://cloud.githubusercontent.com/assets/21176790/19782236/e26833a2-9c5a-11e6-8d00-819134734bcc.png">

**Comment by Zaidwerd** [comment]
@gittheking
@jasonseminara
@trevorpreston
@irwintsay

**Comment by gittheking** [comment]
@Zaidwerd is this still an issue?
